### ISSUE TITLE
Unexpected results within XML Report

### ISSUE THREAD

**Issue by koerbcm** [larrymyers/jasmine-reporters#100]
I don't really know where to leave this and not sure if its a bug, or I am doing something wrong, so any advice would help.

**Description**
When I run test suites, I get a spec output that looks correct, but when I look at the xml report, and then Jenkins imports it, the results don't seem correct. 

I have some tests with nested describe statements, then I have others that do not. If the first spec run, does not have nested describe blocks or there are it statements in the top most parent, I get a test suite called focused.spec and the first it statements fall outside of their parent describe. 

**Issue**
The issue I am having is when Jenkins displays the xml report, all the it blocks within the first test show up in a 'root' directory. All top level suites are within a focused.spec directory. All children describe blocks show up at the top level with root and focused spec. 

**Spec Reporter Results**

    /usr/local/bin/node /Users/blah/node_modules/protractor/lib/cli.js /Users/blah/workspace/ui/src/config/config.js
    Using the selenium server at http://localhost:4444/wd/hub
    [launcher] Running 1 instances of WebDriver
    Spec started

      1 Test 1
        ✓ it 1 (0.007 secs)
        ✓ it 2 (0.003 secs)
        ✓ it 3 (0.01 secs)
        ✓ it 4 (0.002 secs)
        ✓ it 5 (0.002 secs)
        ✓ it 6 (0.005 secs)
        ✓ it 7 (0.005 secs)
        ✓ it 8 (0.003 secs)
        ✓ it 9 (0.002 secs)
        ✓ it 10 (0.003 secs)
        ✓ it 11 (0.002 secs)
        ✓ it 12 (0.003 secs)

      2 Test 2

        2.1 describe 1
          ✓ it 1 (0.003 secs)
          ✓ it 2 (0.002 secs)

        2.2 describe 2
          ✓ it 3 (0.003 secs)

          2.2.1 describe3
            ✓ it 4 (0.002 secs)
            ✓ it 5 (0.003 secs)
            ✓ it 6 (0.017 secs)
            ✓ it 7 (0.005 secs)

        2.3 describe 4
          ✓ it 8 (0.004 secs)

          2.3.1 describe 5
            ✓ it 9 (0.004 secs)
            ✓ it 10 (0.007 secs)
            ✓ it 11 (0.006 secs)
            ✓ it 12 (0.004 secs)

    Executed 24 of 24 specs SUCCESS in 8 secs.
    [launcher] 0 instance(s) of WebDriver still running
    [launcher] chrome #1 passed

    Process finished with exit code 0

**XML Output***

    <?xml version="1.0" encoding="UTF-8" ?>
    <testsuites>
        <testsuite name="focused specs" timestamp="2015-06-10T09:51:15" hostname="localhost" time="4.66" errors="0" tests="12" skipped="0" disabled="0" failures="0">
            <testcase classname="focused specs" name="it 1" time="0.007">
            </testcase>
            <testcase classname="focused specs" name="it 2" time="0.003">
            </testcase>
            <testcase classname="focused specs" name="it 3" time="0.01">
            </testcase>
            <testcase classname="focused specs" name="it 4" time="0.003">
            </testcase>
            <testcase classname="focused specs" name="it 5" time="0.002">
            </testcase>
            <testcase classname="focused specs" name="it 6" time="0.005">
            </testcase>
            <testcase classname="focused specs" name="it 7" time="0.005">
            </testcase>
            <testcase classname="focused specs" name="it 8" time="0.003">
            </testcase>
            <testcase classname="focused specs" name="it 9" time="0.002">
            </testcase>
            <testcase classname="focused specs" name="it 10" time="0.003">
            </testcase>
            <testcase classname="focused specs" name="it 11" time="0.002">
            </testcase>
            <testcase classname="focused specs" name="it 12" time="0.003">
            </testcase>
        </testsuite>
        <testsuite name="focused specs.Test 1" timestamp="2015-06-10T09:51:15" hostname="localhost" time="0" errors="0" tests="0" skipped="0" disabled="0" failures="0">
        </testsuite>
        <testsuite name="focused specs.Test 2" timestamp="2015-06-10T09:51:15" hostname="localhost" time="4.22" errors="0" tests="0" skipped="0" disabled="0" failures="0">
        </testsuite>
        <testsuite name="focused specs.Test 2.describe 1" timestamp="2015-06-10T09:51:19" hostname="localhost" time="0.005" errors="0" tests="2" skipped="0" disabled="0" failures="0">
            <testcase classname="focused specs.Test 2.describe 1" name="it 1" time="0.003">
            </testcase>
            <testcase classname="focused specs.Test 2.describe 1" name="it 2" time="0.002">
            </testcase>
        </testsuite>
        <testsuite name="focused specs.Test 2.describe 2" timestamp="2015-06-10T09:51:19" hostname="localhost" time="0.03" errors="0" tests="1" skipped="0" disabled="0" failures="0">
            <testcase classname="focused specs.Test 2.describe 2" name="it 3" time="0.002">
            </testcase>
        </testsuite>
        <testsuite name="focused specs.Test 2.describe 2.describe3" timestamp="2015-06-10T09:51:19" hostname="localhost" time="0.027" errors="0" tests="4" skipped="0" disabled="0" failures="0">
            <testcase classname="focused specs.Test 2.describe 2.describe3" name="it 4" time="0.002">
            </testcase>
            <testcase classname="focused specs.Test 2.describe 2.describe3" name="it 5" time="0.003">
            </testcase>
            <testcase classname="focused specs.Test 2.describe 2.describe3" name="it 6" time="0.017">
            </testcase>
            <testcase classname="focused specs.Test 2.describe 2.describe3" name="it 7" time="0.005">
            </testcase>
        </testsuite>
        <testsuite name="focused specs.Test 2.describe 4" timestamp="2015-06-10T09:51:19" hostname="localhost" time="0.025" errors="0" tests="1" skipped="0" disabled="0" failures="0">
            <testcase classname="focused specs.Test 2.describe 4" name="it 8" time="0.004">
            </testcase>
        </testsuite>
        <testsuite name="focused specs.Test 2.describe 4.describe 5" timestamp="2015-06-10T09:51:19" hostname="localhost" time="0.021" errors="0" tests="4" skipped="0" disabled="0" failures="0">
            <testcase classname="focused specs.Test 2.describe 4.describe 5" name="it 9" time="0.004">
            </testcase>
            <testcase classname="focused specs.Test 2.describe 4.describe 5" name="it 10" time="0.007">
            </testcase>
            <testcase classname="focused specs.Test 2.describe 4.describe 5" name="it 11" time="0.006">
            </testcase>
            <testcase classname="focused specs.Test 2.describe 4.describe 5" name="it 12" time="0.004">
            </testcase>
        </testsuite>
    </testsuites>

**Comment by bloveridge** [comment]
Are you using `fit` or `fdescribe` anywhere? When focusing specs / suites, Jasmine does not send the `suiteStarted` and `suiteDone` events, which is how jasmine-reporters deciphers the test hierarchy. To make things still kind of work correctly, jasmine-reporters lumps things into a fake `focused specs` suite, which looks like what you are seeing. The *only* time jasmine-reporters inserts `focused specs` is if it doesn't receive the `suiteStarted` event.

Another time this might happen is if you don't get the reporter set up before jasmine starts executing. With Protractor, one common way this can happen is if you are using `getProcessedConfig` inside your `onPrepare` handler but not returning that promise -- it inside your onPrepare function should be something like `return browser.getProcessedConfig().then( ... )` (see the README for a complete example).

**Comment by koerbcm** [comment]
Thank you for your response. I was laid off, so can't really get this working, but I appreciate your time. Thanks again.
