### ISSUE TITLE
Print only jasmine focused tests

### ISSUE THREAD

**Issue by alecxe** [larrymyers/jasmine-reporters#107]
The detailed problem description is in this [stackoverflow post](http://stackoverflow.com/questions/31352806/print-only-jasmine-focused-tests). 

The problem can actually be interpreted as: 
Can we make the `TerminalReporter` be verbose with focused tests and silent with disabled tests?

**Comment by bloveridge** [comment]
If this functionality is important to you, please feel free to create a PR. To not change behavior for any existing users, my first instinct would be to create an additional config option, like `suppressDisabledSpecs = true` or similar.
