### ISSUE TITLE
Too Much Recursion Error with page.evaluate running on SlimerJS for JUnitXmlReporter

### ISSUE THREAD

**Issue by kzeng10** [larrymyers/jasmine-reporters#110]
I'm trying to export test results from Jasmine using a JUnitXmlReporter to report results to Jenkins. However, when I do so, I get a `An exception occurred InternalError: too much recursion` error, followed by thousands of lines that point towards `bin/phantomjs-testrunner.js at line 117 column 57 in overloadPageEvaluate/page.evaluate`.

**Comment by treywashington** [comment]
Still trying to find a solution to this one. Worth noting that overloadPageEvaluate and setupWriteFileFunction are called twice whereas setupPageFn is called once.

**Comment by treywashington** [comment]
try `xvfb-run slimerjs phantomjs-testrunner.js  file://path/to/test-runner.html` instead of just `xvfb-run slimerjs phantomjs-testrunner.js test-runner.html`

**Comment by treywashington** [comment]
Not a true fix but Slimerjs doesn't seem to like overloading, this will work if you go through and replace page.evaluate with this method:
```
function evaluate(page, fn, replacements) {
    return page.evaluate(replaceFunctionPlaceholders(fn, replacements));
}
```

**Comment by bloveridge** [comment]
If that works, it doesn't sound like a bad fix at all. The original page.evaluate overloading code was written many years ago, and likely was not the best way of doing things. I've verified that changing the code to use your pattern and it all seems to work fine when used standalone, so I pushed this into master for the next release. @kzeng10 and @treywashington it would be great if you can confirm that it works as expected in Slimer before I tag and ship another release.
