### ISSUE TITLE
Capture console.log output in xmloutput.xml

### ISSUE THREAD

**Issue by madhavan020985** [larrymyers/jasmine-reporters#114]
I am running protractor with jasmine-reporters plugin. The generated xmloutput.xml contains information about test status-es.

In addition to this, i would like to get the console.log messages as well, under the testcase xml node
like,
````xml
<testsuite name="AP List: ." timestamp="2015-08-31T22:24:02" hostname="localhost" time="10.589" errors="0" tests="1" skipped="0" disabled="0" failures="0">
<testcase classname="AP List: .When loading AP list" name="Should list APs " time="10.589">
<message> this is a dummy message logged in.....</message>
<message>........................................</message>
</testcase>
</testsuite>
````

This helps the end-users to understand the test specs better. Is there a way i can do it?

**Comment by vurt007** [comment]
+1

**Comment by scriby** [comment]
+1
