### ISSUE TITLE
writing report failed

### ISSUE THREAD

**Issue by vanatomas** [larrymyers/jasmine-reporters#115]
Hi, whan I add into conf.js file to get reports, I do get error on permissions

Started
FWarning: writing junit report failed for 'testresults', 'xmloutput.xml'. Reasons:
  PhantomJs attempt: window is not defined
  NodeJS attempt: EACCES, permission denied '/usr/local/lib/node_modules/protractor/example/testresults'

Is there a way to fix it?

**Comment by bloveridge** [comment]
It's hard to tell fully from the information you have provided, but it looks like it is attempting to write test output into a child of `/usr/local/lib`, which may require privileged access. At any rate, it looks like there is a permissions error on the destination you are trying to write your output to. Check your configuration and try again.
