### ISSUE TITLE
Documentation for using with jasmine-node?

### ISSUE THREAD

**Issue by synthecypher** [larrymyers/jasmine-reporters#116]
I'm trying to get the reporters working with `jasmine-node`.

Do I need to install `jasmine`, `jasmine-node`, and `jasmine-reporters` into my npm module? or just `jasmine-node` and `jasmine-reporters`?

Then how do I connect `jasmine-reporters` to `jasmine-node`?

![image](https://cloud.githubusercontent.com/assets/1833542/9629871/f49dcc82-516d-11e5-8bec-d00006ee9b40.png)

**Comment by bloveridge** [comment]
`jasmine-node` takes care of requiring `jasmine-reporters` in its package.json. If you are using jasmine-node, you should be able to pass `--junit` to get junit reports via jasmine-reporters.

Please see [jasmine-node](https://github.com/mhevery/jasmine-node/tree/Jasmine2.0) for information on how to use that project.

I will note, however, that jasmine-node seems to be only mildly maintained these days and is not the recommended way for using Jasmine 2.x for node tests. In most cases, you should use the official [jasmine-npm](https://github.com/jasmine/jasmine-npm) instead.
