### ISSUE TITLE
Dynamic generated filePrefix

### ISSUE THREAD

**Issue by tschiela** [larrymyers/jasmine-reporters#119]
We run our test on multiple urls. E.g. Test A run on domain1 and domain2. The problem is, that after the test are completed, the results of domain1 got overwritten by the results of domain2. 

My idea: the option filePrefix could be a string (as it currently is) or it could be a callback. So we could do something like:

```javascript
filePrefix: function(){
  return 'someTestName-' + browser.someVar;
}
```

If this make sense for you, i could create a PR for that.

**Comment by bloveridge** [comment]
Have you looked into the modifySuiteName option? This was introduced to solve problems like the one you describe and may be sufficient for your needs. See the README for an example.

**Comment by tschiela** [comment]
We are doing something like:

```javascript
describe('some test', function(){
  for(var i = 0; urlLen = urs.length; i < urlLen; i++){
    beforeEach(...);
    it(....);
      it(....);
  }
});
```

It seems like that overwrite the existing *.xml files

**Comment by tschiela** [comment]
I found a simple solution for that. I put the describe also in the for loop. 
```javascript
for(var i = 0; urlLen = urs.length; i < urlLen; i++){
  describe('some test', function(){ 
    beforeEach(...);
    it(....);
    it(....);  
  });
}
```

**Comment by bloveridge** [comment]
Glad you found a solution.
