### ISSUE TITLE
using jasmine-reporters with the accessibility plugin

### ISSUE THREAD

**Issue by david-gang** [larrymyers/jasmine-reporters#120]
Hi,

This is connected to http://stackoverflow.com/questions/29913799/report-accessibility-plugin-results

I want to use the jasmine-reporters plugin to create a report on protractor and the accessibility plugin.

As i understand this does not work out of the box and i have to process the json output. This is because the plugin events are not emitted.

Is there a way to use jasmine-reporters in any way to make the parsing  of the json file. Maybe to use it somehow as post processor?

Thanks,
David

**Comment by bloveridge** [comment]
Hi David. As Poijted out in the answer on that SO article, the primary problem here is that the plugin does not emit Jasmine events, so jasmine-reporters (or other custom Jasmine reporters) doesn't receive anything to react to. 

Jasmine-reporters Is only designed to work in within a Jasmine environment and responding to those events, and does not have the ability to post process arbitrary files and output XML. You can certainly use jasmine-reporters as an example of what properties you may want to include in your XML, but you may be better off writing a custom xslt to convert your JSON or finding some other tool designed for that purpose. 

If you do roll your own, the Junit schema definition is available on GitHub, which you can reference to ensure you write a valid junit-style XML. https://github.com/windyroad/JUnit-Schema

**Comment by david-gang** [comment]
Thanks for your quick response,
David
