### ISSUE TITLE
Allow for blank string file prefixes

### ISSUE THREAD

**Issue by aakilfernandes** [larrymyers/jasmine-reporters#124]
https://github.com/larrymyers/jasmine-reporters/blob/jasmine1.x/src/jasmine.junit_reporter.js#L56

B/c the prefix is checked for falsey rather than undefined, prefixes of `''` cannot be set

**Comment by aakilfernandes** [comment]
Looks like this is fixed for the 2.x branch but not the 1.x. I believe some tools (protractor) only work with 1.x

**Comment by bloveridge** [comment]
I did indeed only fix it on the 2.x branch. Are you using 1.x? Some tools only work with 1.x, but protractor is not one of them (I use protractor with jasmine2 daily).
