### ISSUE TITLE
Report Generation Tool

### ISSUE THREAD

**Issue by archanamuplamreddy** [larrymyers/jasmine-reporters#131]
Is there any other report generation tool except than jasmine-reporters.To get more information about testoutput?
Currently using jasmine-reporters integrated with protractor.

**Comment by Crevil** [comment]
What information do you need?
If you [google it](https://goo.gl/TaeRKk), you'll find others. Like:

* [jasmine-spec-reporter](https://www.npmjs.com/package/jasmine-spec-reporter)
* [jasmine-terminal-reporter](https://www.npmjs.com/package/jasmine-terminal-reporter)

**Comment by bloveridge** [comment]
As noted, there are many alternative and supplementary reporters available for jasmine beyond those included in this repository. It is outside the scope of this project or its documentation to provide a list of all such reporters.
