### ISSUE TITLE
ConsolidateAll option for NUnit reporter

### ISSUE THREAD

**Issue by ivantsov** [larrymyers/jasmine-reporters#132]
There is a `consolidateAll` option in JUnit reporter to save results in a separate file for each test case. But NUnit reporter doesn't provide such option... Is there some reason for that or it just because you don't have time to do that? 

Nevertheless, thank you for work on this project!

**Comment by bloveridge** [comment]
It's not been a priority nor a frequently requested feature. As such I don't anticipate spending any time developing such a solution myself, but I'm open to pull requests if you would like to add this functionality yourself. If so, please use the same options and naming conventions wherever possible to provide as much cohesion as possible between the reporters.
