### ISSUE TITLE
Multi Capabilities error

### ISSUE THREAD

**Issue by nvsoares** [larrymyers/jasmine-reporters#133]
when use the example that is in the documentation for the multi-capabilities, i can not perform the tests. The whole process is given as being done all the tests in error. The strange thing is that it is not given any message that allows to know the source of the error.

**Comment by bloveridge** [comment]
There's not enough information in this to be actionable, and the `modifySuiteName` and `modifyReportFileName` delegates as described in the documentation are being successfully used by many people. I'm closing this issue for now, but if it is still causing you problems then feel free to re-open the issue with more details, or even better to submit a pull request that addresses the issue.
