### ISSUE TITLE
Issue in the JUnitXmlReporter when running with the property shardTestFiles=true in protractor

### ISSUE THREAD

**Issue by vivekbrahmadandi** [larrymyers/jasmine-reporters#140]
Issue is the reporter doesnt include the all the test results which ran, it is including only the last executed test suite in the results

**Comment by Xotabu4** [comment]
Is there any solution for this?

**Comment by vivekbrahmadandi** [comment]
dont know repo owner should comment on it for a solution,

**Comment by Xotabu4** [comment]
@vivekbrahmadandi Trying with - https://github.com/bhovhannes/junit-report-merger
I think it should help.

**Comment by bloveridge** [comment]
I suggest looking into the helper @Xotabu4 suggested, or using a combination of the various delegate options that have recently been added, such as `modifySuiteName` and `modifyReportFileName`. Beyond that, I have no experience with `shardTestFiles=true` with Protractor and, if I'm honest, will probably not spend a lot of time looking into alternative solutions. I am, however, open to merging pull requests providing solutions for the issue.
