### ISSUE TITLE
Junit results are not guaranteed to be unique when uploading to Visual Studio

### ISSUE THREAD

**Issue by zumwald** [larrymyers/jasmine-reporters#141]
The TestCase name is only set to the spec description, so if multiple specs use some generic description then the test results can't be differentiated after the fact.

Could an extension method be exposed similar to modifySuiteName, something like modifyTestName so that if one desires to add metadata to the TestCase name, they can?

**Comment by zumwald** [comment]
resolved with #142

**Comment by bloveridge** [comment]
#142 merged. Closing.
