### ISSUE TITLE
 jasmine reporter giving error AfterAll TypeError with jasmine 2

### ISSUE THREAD

**Issue by Saurabh06** [larrymyers/jasmine-reporters#146]
When i am using jasmine reporter in script using jasmine 2 framework and protractor 3.x:
 jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            consolidate: true,
            consolidateAll: true,
            savePath: '...',
            filePrefix: 'xmloutput'
        }));

I am getting below error using chrome browser: 
![image](https://cloud.githubusercontent.com/assets/17181080/16225954/e029e980-37c6-11e6-9a53-c8bfcfcb5e19.png)

**Comment by bloveridge** [comment]
I think this has been addressed with other PRs that have been merged and released in the last 6 months. Feel free to re-open with an example test case if the problem persists.
