### ISSUE TITLE
Enable run-time logging for every test-suite.

### ISSUE THREAD

**Issue by channox32** [larrymyers/jasmine-reporters#152]
I need to enable on run-time logging since I'll be exposing the results as REST API. 
How to do these ?

**Comment by bloveridge** [comment]
You could implement something like this by capturing console output from something like the TAP reporter and parsing it, or you could write a custom reporter to do what you need. None of the existing reporters have lifecycle hooks like that. If you wanted to do something like expose the JUnit results after the reporter is finished, you could write your own mini-reporter that registers only the `jasmineDone` callback, and then use that to know when to look for the XML file, or something similar.

It's not clear to me exactly what you are looking for, but a new / custom reporter may be what you're looking for. If it's a generalized reporter that would be beneficial to many, feel free to make a pull request and we'll consider adding it to this project.
