### ISSUE TITLE
Add optional ability to save spec results into xml file or some temp files on the fly 

### ISSUE THREAD

**Issue by antohaUa** [larrymyers/jasmine-reporters#153]
If tests run failed due to raised exception -  user will be not able to collect execution run data, cause now write to xml files operation performed only at the end of all.

Please add optional ability that will allow write to xml file ( or some temporary files) on the fly

This will give opportunity to user after exception for example fix by himself incomplete xml file ( or collect info from temp files)  and get not only exception but also results about items tested before crash.

**Comment by bloveridge** [comment]
Feel free to create a PR with the proposed behavior.
