### ISSUE TITLE
Add ability to prevent Jest Jasmine to output non UTF-8 to the junit.xml file

### ISSUE THREAD

**Issue by rexyeung** [larrymyers/jasmine-reporters#155]
When using the JUnitXmlReporter module with JEST 16.0.1 snapshots, the output xml has some non UTF-8 values which an xml parser can't parse. 

Would you be able to add a way to prevent this from happening?

**Comment by thaggie** [comment]
This PR https://github.com/larrymyers/jasmine-reporters/pull/156 is a fix for this issue.
