### ISSUE TITLE
If the first describe is the same for different specs, which should be startet in own browser session -there are some difficulties with generating XML-Reports.

### ISSUE THREAD

**Issue by vinogradoff** [larrymyers/jasmine-reporters#163]
I have put the question on Stackoverflow, but perhaps that can be solved only through fix in the framework.

http://stackoverflow.com/questions/42591171/jasminereporter-junitxmlreporter-overwrites-the-results-of-the-run
---------------------------
My specs share the same first describes (the second is different) e.g.

**spec1.js:**

    describe("topic1",()=> {
      describe("testcase1",()=> {
       ...
      });
    });

**spec2.js:**
    
    describe("topic1",()=> {
      describe("testcase2",()=> {
       ...
      });
    });

which works fine if I run the both specs in the same browser like:

    protractor --specs spec1.js,spec2.js config.js

But as I want to restart the browser between runs of spec1.js and spec2.js with either:

    protractor --specs spec1.js config.js; protractor --specs spec2.js config.js

or setting in capabilites:

    shardTestFiles: true

then the `junitresults.xml` resp. `junitresults-topic1.xml` (depending on `consolidateAll` option being`true` or `false`) is generated containing only the results of the last spec (spec2.js) run.

How can I get all the runs in my XML results?

**Comment by bloveridge** [comment]
This issue seems related to both #175 and #149.
