### ISSUE TITLE
Is there a way to create jUnitXML reporter in the beginning of a protractor run

### ISSUE THREAD

**Issue by nareshsurya** [larrymyers/jasmine-reporters#171]
Hi Team,
Usually, JUnit XML reporter will generate after the execution of protractor spec completed. Because of this, we are not getting log file which is not generated due to an unexpected exception during the execution.

I want a way to create a reporter before starting off the run and append the console info during the execution.

Can someone please suggest me a way?

Regards,
Naresh Surya

**Comment by bloveridge** [comment]
None of our file-based reporters are currently set up in such a way that they could create a file initially, then either append or replace it as results arrive. This sounds like something more suited to the terminal reporter, or one of the other console-based reporters.
