### ISSUE TITLE
Best TAP reporter for protractor?

### ISSUE THREAD

**Issue by ORESoftware** [larrymyers/jasmine-reporters#172]
Can you honestly say that this is the best TAP reporter for Protractor?

Just trying to find the best one to use. Thanks!

**Comment by yeikel** [comment]
what is the definition of "best" ?

**Comment by bloveridge** [comment]
Subjective inquiry, and I've not done an analysis of other available TAP reporters. If you encounter ways this TAP reporter falls flat, please consider creating a pull request with the necessary improvements so others can share the benefits.

**Comment by ORESoftware** [comment]
definition of best? the one your mom would want to use
