### ISSUE TITLE
Is there any way to write the results of TerminalReporter to a file?

### ISSUE THREAD

**Issue by yeikel** [larrymyers/jasmine-reporters#182]
As the title suggests, is there any way to write the results of TerminalReporter to a file?

**Comment by bloveridge** [comment]
This library does not include any native support for writing the results of TerminalReporter to a file. JUnit and NUnit results get written to file, the rest are written to stdout where they are expected to be parsed by some other tool, such as TeamCity, etc. The mechanism whereby you would capture the TerminalReporter output to file will depend on what your test environment is like. For example, if you're using the included examples from a command prompt, you could redirect stdout to some file e.g. `./bin/phantomjs.runner.sh examples/terminal_reporter.html > testresults`.
