### ISSUE TITLE
npmjs reports latest is 2.3.0 but latest release/tags in github is 2.2.1?

### ISSUE THREAD

**Issue by rasjani** [larrymyers/jasmine-reporters#183]
Just wondering if the release is valid ? Ran a diff between releases and it did look ok .. 

Maybe you could push the tag here to pinpoint where 2.3.0 was actually done ?

**Comment by lexxanatoli** [comment]
Any updates here? The problem is still not solved.

**Comment by bloveridge** [comment]
Sorry, I forgot the push the tag to Github when I published to npm. That's been pushed now.
