### ISSUE TITLE
A new release and a new upload to npm ~2.5.1 would be nice.

### ISSUE THREAD

**Issue by harsha509** [larrymyers/jasmine-reporters#211]
Hi There,

Would like to request if there can be a new minor/patch release which fixes @xmldom/xmldom dependantbot issue!

**Comment by nekvinder** [comment]
+1

**Comment by mikeappell** [comment]
FYI, it looks like right now you can pin your dependency to commit `0ccfc0f3a85458cf23d042e08e61af74dfdd5dd9` to include an upgrade to xmldom/xmldom. That commit includes that update as well as changing the release name to 2.5.1.

Though obviously it would be nice to have a named, targetable release number for this.

**Comment by RainOfPhone** [comment]
Hi, I see that @xmldom/xmldom's version is ^0.8.3 in this repo, but it's still version ^0.7.3 in npmjs.com. How long it will take that publish the latest version to npmjs.com?
Best Regards.

**Comment by larrymyers** [comment]
@putermancer owns the package on npm, and will need to handle publishing the new version.

**Comment by kevcenteno** [comment]
Is @putermancer still active?  I don't see much on his github activity, It may be prudent to add you (@larrymyers) to the collaborators list on npm so you can do releases.

**Comment by putermancer** [comment]
v2.5.1 has been published to npm. Thanks again for pinging me, and thanks @larrymyers for getting the MR in question merged in. I've invited you as a maintainer on npmjs as well; what you do with that is up to you.

Like @larrymyers, I (obviously) devote very little attention to this package anymore. Most of my work is private sector and, while I still make use of this project in a couple places, it's been relatively stable for years, the junit reporter has always been the star of the show for me, and most frameworks support junit these days.

Like @larrymyers, I would support an active community fork. Once established, we could either deprecate the current package in npmjs in favor of a new community release or add appropriate maintainers to the current package.

For now, I'm still around and pay sporadic attention to the activity here; quick turnaround is not assured.
