### ISSUE TITLE
Release/Tag for npm 2.5.2 Missing

### ISSUE THREAD

**Issue by davmillar** [larrymyers/jasmine-reporters#215]
Howdy, thank you for your hard work maintaining this package.

Yarn is advising that version 2.5.2 is available, but there's no release or tag in the repo here to reference and review prior to upgrade. Could a maintainer please tag that release so that I could compare with the current version we have installed? Using the GitHub release feature and adding a changelog would be even better, but I know folks are super busy so no worries if that's a step too far. :)

Thanks again!

**Comment by putermancer** [comment]
Tags for 2.5.0, 2.5.1, and 2.5.2 have just been pushed.

**Comment by davmillar** [comment]
Thanks a ton!
