### ISSUE TITLE
Super small test duration

### ISSUE THREAD

**Issue by mitchhentges** [larrymyers/jasmine-reporters#76]
I'm seeing test durations of < 10ms, which is impossible.
This is when reporting to TeamCity.
![testduration](https://cloud.githubusercontent.com/assets/7784737/5598631/addbefa4-926e-11e4-9d75-6a9a3c346c6a.png)

**Comment by bloveridge** [comment]
What, precisely, is your concern? Is there something specific to the environment your tests are running within, or the tests themselves, that gives you the certainty that 10ms is impossible? It is quite possible for many jasmine tests to run in under 10ms, and many simple tests even execute within 1ms as pictured in your screenshot when run on good hardware.

The timestamp jasmine-reporters generates when writing console messages for TeamCity is pretty straightforward:

    // we create the timestamp like this for each message output to the console for TeamCity
    attrs.timestamp = new Date();

    // we then run it through the following function to make it an ISO-8601 string
    // "pad" ensures a number is two digits, ie "2" -> "02"
    // "pad3" ensures a number is three digits, ie "2" -> "002"
    function ISODateString(d) {
        return d.getUTCFullYear() + '-' +
            pad(d.getUTCMonth()+1) + '-' +
            pad(d.getUTCDate()) + 'T' +
            pad(d.getUTCHours()) + ':' +
            pad(d.getUTCMinutes()) + ':' +
            pad(d.getUTCSeconds()) + '.' +
            // TeamCity wants ss.SSS
            padThree(d.getUTCMilliseconds());
    }

I'm really just confused as to what the actual issue you are reporting is. You didn't provide enough information for me to identify and fix a specific bug, and nothing in the implementation seems obviously flawed.

Please feel free to re-open the issue with information about a specific, reproducible bug.

**Comment by mitchhentges** [comment]
Oh, whoops, forgot a whole lot of context here.
I'm using Protractor for running my end-to-end tests, and it generally takes _at least_ two seconds per test due to driver communication speed.

Protractor goes through the list of commands in an `it`, then queues them all in the "Webdriver queue". Each command returns a promise.

The reason why `jasmine-reporters` says that there is a `10ms` test duration is because the `it` finishes executing before the commands are actually done by the browser.

Is there any way to accurately wait for each promise in the `it` to resolve before considering it done?
