### ISSUE TITLE
Version 2.x not on npm

### ISSUE THREAD

**Issue by vinsonchuong** [larrymyers/jasmine-reporters#78]
The current [npm release](https://www.npmjs.com/package/jasmine-reporters) is on version 1.0.1. Are there plans to release version 2?

**Comment by bloveridge** [comment]
Version 2 has been released on npm. Unfortunately, npmjs.com only shows that most recently published version in the "Package Info" section, and there were some bug fixes to the Jasmine 1.x code more recently than the Jasmine 2.x code.

`jasmine-reporters` does not maintain backwards compatibility in the 2.x version, we continue to publish new 1.x and 2.x versions. This can confuse npmjs.com, unfortunately.

`npm info` will show you the full list of available versions.

```bash
$ npm info jasmine-reporters
{ name: 'jasmine-reporters',
  description: 'Reporters for the Jasmine BDD Framework',
  'dist-tags': { latest: '1.0.1' },
  versions:
   [ '0.1.0',
     '0.2.0',
     '0.2.1',
     '0.3.0',
     '0.3.2',
     '0.4.0',
     '0.4.1',
     '1.0.0',
     '1.0.1',
     '2.0.0',
     '2.0.1',
     '2.0.2',
     '2.0.3' ],
 ...
```
