### ISSUE TITLE
Protractor is using Jasmine 2.0 now, please update the README

### ISSUE THREAD

**Issue by mohsen1** [larrymyers/jasmine-reporters#82]
[Protractor section](https://github.com/larrymyers/jasmine-reporters#protractor) in README is not accurate according to [this](https://github.com/angular/protractor/blob/19139272d190dd9c1888d9c3fc2f480f7c6c8edb/docs/jasmine-upgrade.md)

**Comment by bloveridge** [comment]
Thanks for alerting me to this, I didn't realize protractor had added support for jasmine2 in v1.6.0. I've updated the README with a new example, and moved the 1.x example into the README on the jasmine1.x branch.

**Comment by mohsen1** [comment]
Cool! BTW `npm install --save-dev jasmine-reporters@~2.0.0` can be `npm install --save-dev jasmine-reporters@~2` to allow minor and patch versions

**Comment by bloveridge** [comment]
I considered updating it to use caret syntax, which I think I'll do as it's the default way npm saves it anyway. I'll tweak it to `npm install --save-dev jasmine-reporters@^2.0.0` which still includes all parts but allows full flexibility for anything < 3.0.0
