### ISSUE TITLE
strict mode controlled by reporter?

### ISSUE THREAD

**Issue by karlkras** [larrymyers/jasmine-reporters#97]
We've run into an odd issue here.
In our dev environment we have two modes for using phantomJS for performing our javascript tests.
When processed locally we're simply running the tests through the jasmine console reporter while when run under our bamboo build system we use the NUnitXmlReporter.

A recently added module test set resulted in a clean test run locally, but when run in bamboo these new tests all resulted in a "TypeError: setting a property that has only a getter" error.
This was a valid error since there was a property in this module that only provided a getter accessor.
Looking into why/when such an error is generated appears to be when use strict mode is used.
We don't explicitly set strict mode so I'm curious why when run under the console reporter we don't see this same result? How/where would strict mode be turned on?

**Comment by bloveridge** [comment]
I'm guessing this has something to do with how Bamboo runs the unit tests. You could try running the JUnit reporter locally, like you do the console reporter, and see if you get different results, but there is no code in jasmine-reporters which enables strict mode. I strongly suspect the difference here is how your tests are being run, not which reporter from jasmine-reporters you have enabled.

More about how to enable strict mode per-file, per-function, and strict mode in general is available at MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

**Comment by karlkras** [comment]
Hey Ben, yes, I did run it locally with the nunit runner (not junit) as you recommended and it too is showing this dependency.

**Comment by bloveridge** [comment]
If you run locally, it works fine with the console reporter (from jasmine core) but not if you add a reporter from jasmine-reporters?

What mechanism are you using to run the tests locally? `phantomjs-testrunner.js` from the jasmine-reporters repo? Etc. Maybe that will help track down where the difference is coming into play.

**Comment by bloveridge** [comment]
Another thing you can look into is whether any of the external dependencies you are using, etc. is declaring strict mode in global scope. I've done a recursive grep and I'm not finding any instances of "use strict" in any of the jasmine-reporters code or its dependencies.

See http://stackoverflow.com/questions/19221377/how-to-turn-off-strict-mode-when-using-phantomjs and related questions where people have had to dig to find problems like yours.

**Comment by bloveridge** [comment]
You could also try upgrading to PhantomJS 2.0 and see if the problem persists.

https://github.com/ariya/phantomjs/issues/10889
