### ISSUE TITLE
Protractor "fit"

### ISSUE THREAD

**Issue by sagivf** [larrymyers/jasmine-reporters#98]
When using jasmine 2 with protractor the fit causes 0 tests to run.

**Comment by bloveridge** [comment]
This ticket lacks sufficient detail, and I use `fit` regularly with jasmine-reporters and protractor 2.x without problem.

Are you still having this problem? If so, please re-open with sufficient detail for this to be reproduced and consider creating a PR that addresses the problem you're having.
