### ISSUE TITLE
Feature request: reporter for lcov

### ISSUE THREAD

**Issue by noahsw** [larrymyers/jasmine-reporters#99]
It'd be awesome if there was a reporter to export lcov data. Thanks in advance!

**Comment by reppners** [comment]
Shouldn't this be possible by instrumenting your code-base with https://github.com/gotwarlost/istanbul and then generate the code coverage with it? Maybe this article can give you some insights https://bryce.fisher-fleig.org/blog/setting-up-istanbul-with-jasmine/

**Comment by bloveridge** [comment]
Not currently planned. If pursuing Istanbul as @reppners suggests does not get you what you are looking for, please consider creating the expected functionality yourself and submitting a PR with the new reporter -- jasmine-reporters is always happy to include additional reporters.
